--Q1
SELECT ENAME, SAL, COMM
FROM EMP
WHERE COMM IS NOT NULL
ORDER BY 2 DESC, 3 DESC;

--Q2
SELECT DISTINCT JOB
FROM EMP;
--Q3
SELECT EMPNO AS "Emp #",
       ENAME AS "Employee",
       JOB AS "Job",
       HIREDATE AS "Hire Date"
FROM EMP;
--Q4
SELECT ENAME || ', ' || JOB AS "Employee and Title"
FROM EMP;
--Q5
SELECT ENAME || ',' ||
       JOB || ',' ||
       HIREDATE || ',' ||
       MGR AS THE_OUTPUT
FROM EMP;
--Q6
SELECT ENAME, JOB, HIREDATE
FROM EMP
WHERE ENAME IN ('SCOTT','TURNER')
ORDER BY HIREDATE ASC;
--Q7
SELECT ENAME, DEPTNO
FROM EMP
WHERE DEPTNO IN (20,30)
ORDER BY ENAME;
--Q8
SELECT ENAME AS "Employee",
       SAL AS "Monthly Salary"
FROM EMP
WHERE SAL BETWEEN 2000 AND 3000
AND DEPTNO IN (20,30);
--Q9
SELECT ENAME, HIREDATE
FROM EMP
WHERE HIREDATE BETWEEN '01-JAN-81' AND '31-DEC-81';
--Q10
SELECT ENAME, SAL
FROM EMP
WHERE SAL > &SALARY;
--Q11
SELECT ENAME, JOB
FROM EMP
WHERE MGR IS NULL;
--Q12
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE MGR=&MGR
ORDER BY &COLUMN_NAME;
--Q13
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE MGR=&MANAGER_ID
ORDER BY &SORT_COLUMN;
--Q14
SELECT ENAME
FROM EMP
WHERE ENAME LIKE '__A%';
--Q15
SELECT ENAME
FROM EMP
WHERE ENAME LIKE '%A%'
AND ENAME LIKE '%S%';
--Q16
SELECT ENAME, JOB, SAL
FROM EMP
WHERE JOB='CLERK'
AND SAL IN (800,950,1300);