--Q1
CREATE TABLE Employee (
    EMPNO NUMBER PRIMARY KEY,
    ENAME VARCHAR2(30),
    SAL NUMBER,
    DEPTNO NUMBER
);
CREATE TABLE Department (
    DEPTNO NUMBER PRIMARY KEY,
    DNAME VARCHAR2(30),
    LOC VARCHAR2(30)
);
ALTER TABLE Employee
ADD CONSTRAINT FK_DEPT
FOREIGN KEY (DEPTNO)
REFERENCES Department(DEPTNO);

--Q2
CREATE TABLE Student (
    ROLLNO NUMBER PRIMARY KEY,
    NAME VARCHAR2(30),
    AGE NUMBER,
    EXAM VARCHAR2(30),
    MARKS NUMBER
);
CREATE TABLE Grade (
    MARKS NUMBER PRIMARY KEY,
    GRADE CHAR(2)
);
ALTER TABLE Student
ADD CONSTRAINT FK_GRADE
FOREIGN KEY (MARKS)
REFERENCES Grade(MARKS);

--Q3
CREATE TABLE Employee_Project (
    EMPNO NUMBER,
    PROJECT_NO NUMBER,
    NO_OF_DAYS NUMBER,
    PRIMARY KEY (EMPNO, PROJECT_NO)
);
CREATE TABLE Project (
    PROJECT_NO NUMBER PRIMARY KEY,
    CUSTOMERNAME VARCHAR2(50)
);
ALTER TABLE Employee_Project
ADD CONSTRAINT FK_PROJECT
FOREIGN KEY (PROJECT_NO)
REFERENCES Project(PROJECT_NO);